name: Main DockerHub fetcher action

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Docker
        uses: docker/build-push-action@v4.1.1
        with:
          build_args: PORT=${{ vars.APP_PORT }}
          tags: ${{ vars.DOCKERHUB_USER }}/${{ vars.DOCKER_IMAGE }}
          pull: true
          push: true
      
